name: maharat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  stacked: ^3.2.2
  # dependency injection and locator
  get_it: ^7.3.0
  injectable: ^2.1.1
  # routing
  auto_route: ^6.4.0
  # api http call and result helper
  retrofit: ^4.0.1
  dio: ^5.1.1
  multiple_result: ^4.0.0
  # styling and widgets
  lottie: ^2.3.2
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  loading_elevated_button: ^1.0.0+2
  conditioned: ^0.1.0-dev.1
  # dependencies and plugins
  localstore: ^1.3.5
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0
  rename: ^2.1.1
  mime: ^1.0.4
  flutter_otp_text_field: ^1.1.1
  country_calling_code_picker: ^2.0.1
  flutter_custom_clippers: ^2.1.0
  expandable_page_view: ^1.0.17
  banner_carousel: ^1.2.1
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  retrofit_generator: ^6.0.0+3
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/
